const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');const root=path.resolve(__dirname,'..');
class Element{
 constructor(tag='div'){this.tagName=tag;this.children=[];this.events={};this.attributes={};this.dataset={};this.style={setProperty(k,v){this[k]=v}};const classes=new Set();this.classList={add:x=>classes.add(x),remove:x=>classes.delete(x),toggle:(x,force)=>{const on=force===undefined?!classes.has(x):force;if(on)classes.add(x);else classes.delete(x);return on},contains:x=>classes.has(x)};this.hidden=false;this.disabled=false;this.value='';this.open=false;this._text='';this.className='';}
 set textContent(v){this._text=String(v)}get textContent(){return this._text+this.children.map(c=>c.textContent).join('')}
 append(...children){this.children.push(...children)}prepend(...children){this.children.unshift(...children)}setAttribute(k,v){this.attributes[k]=v}addEventListener(k,fn){(this.events[k]??=[]).push(fn)}
 dispatch(k,extra={}){for(const f of this.events[k]??[])f({preventDefault(){},stopImmediatePropagation(){},...extra})}click(){if(!this.disabled)this.dispatch('click')}focus(){document.activeElement=this}scrollTo(){}getBoundingClientRect(){return this.rect||{top:0,bottom:60,height:60,width:300}}scrollIntoView(){this.scrolled=true}querySelector(tag){return this.children.find(c=>c.tagName===tag)}showModal(){this.open=true}close(){this.open=false;this.dispatch('close')}
}
const ids={},documentEvents={};const document={documentElement:new Element('html'),activeElement:null,body:new Element('body'),getElementById:id=>ids[id]??=new Element(),createElement:tag=>new Element(tag),createDocumentFragment:()=>new Element('fragment'),querySelector:s=>walk(ids.timeline).find(x=>x.className==='card'&&s.includes(x.dataset.src)),addEventListener:(name,fn)=>(documentEvents[name]??=[]).push(fn)};
function walk(el){return [el,...el.children.flatMap(walk)]}
ids.bgm=new Element('audio');ids.bgm.paused=true;let playCount=0;ids.bgm.play=()=>{playCount++;ids.bgm.paused=false;ids.bgm.dispatch('play');return Promise.resolve()};ids.bgm.pause=()=>{ids.bgm.paused=true;ids.bgm.dispatch('pause')};
const loads=[];class Image{set src(value){this._src=value;loads.push(this)}get src(){return this._src}}
let now=10000;const storage=new Map();const context=vm.createContext({document,Image,Date:{now:()=>now},setTimeout,clearTimeout,window:{scrollY:0,scrollTo(x,y){this.scrollY=y},addEventListener(){}},requestAnimationFrame:fn=>{fn();return 0},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},console});
for(const file of ['photos.js','album.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file});const run=code=>vm.runInContext(code,context);
assert.equal(run('PHOTOS.length'),836);assert.equal(run('new Set(PHOTOS.map(p=>p.src)).size'),836);assert.equal(run('photos.every((p,i)=>i===0||dateKey(photos[i-1])<=dateKey(p))'),true);assert.equal(loads.length,0);
ids.startBtn.click();const cards=walk(ids.timeline).filter(x=>x.className==='card');assert.equal(cards.length,836);assert.equal(ids.cover.hidden,true);assert.equal(ids.album.hidden,false);assert.equal(document.activeElement,ids.yearSelect);assert.equal(playCount,0);
ids.musicBtn.click();assert.equal(playCount,1);assert.equal(ids.musicBtn.attributes['aria-label'],'关闭背景音乐');ids.musicBtn.click();assert.equal(ids.bgm.paused,true);assert.equal(ids.musicBtn.attributes['aria-label'],'播放背景音乐');
const years=walk(ids.timeline).filter(x=>x.className==='year');assert.equal(new Set(years.map(x=>x.id)).size,years.length);assert.equal(years.find(x=>walk(x).some(x=>x.dataset.src==='photos/p502.jpg')).id,'year-2017');assert.equal(cards[0].children[0].loading,'lazy');
// Direct year choice, without a second confirmation button.
ids['year-2026']=years.find(x=>x.id==='year-2026');ids.yearSelect.value='2026';ids.yearSelect.dispatch('change');assert.equal(document.activeElement,ids['year-2026'].querySelector('h2'));
run('window.scrollY=54321');cards[0].click();assert.equal(ids.viewer.open,true);assert.equal(ids.vprev.disabled,true);assert.equal(ids.vcount.textContent,'1 / 836');assert.equal(document.activeElement,ids.vclose);assert.equal(ids.imageFeedback.hidden,false);loads.at(-1).onerror();assert.equal(ids.retryImage.hidden,false);ids.retryImage.click();loads.at(-1).onload();assert.equal(ids.vimg.src,'photos/p001.jpg');
ids.vnext.click();const stale=loads.at(-1);ids.vnext.click();const latest=loads.at(-1);stale.onload();assert.equal(ids.imageFeedback.hidden,false);latest.onload();assert.equal(ids.vcount.textContent,'3 / 836');
// Saving shows instructions alongside the SAME original, without navigation or another dialog.
const before=ids.vcount.textContent,originalSource=ids.vimg.src;
ids.savePhoto.click();assert.equal(ids.viewer.open,true);assert.equal(ids.vcount.textContent,before);assert.equal(ids.vimg.src,originalSource);assert.equal(ids.viewer.classList.contains('show-save-help'),true);assert.equal(ids.saveHelp.attributes['aria-hidden'],'false');assert.equal(ids.captionCopy.attributes['aria-hidden'],'true');assert.equal(ids.savePhoto.textContent,'知道了');
ids.savePhoto.click();assert.equal(ids.viewer.open,true);assert.equal(ids.vcount.textContent,before);assert.equal(ids.vimg.src,originalSource);assert.equal(ids.saveHelp.attributes['aria-hidden'],'true');assert.equal(ids.captionCopy.attributes['aria-hidden'],'false');assert.equal(ids.savePhoto.textContent,'保存');
ids.vclose.click();assert.equal(ids.viewer.open,false);assert.equal(document.activeElement,cards[0]);assert.equal(document.body.style.overflow,'');assert.equal(run('window.scrollY'),54321);
ids.startBtn.click();assert.equal(ids.viewer.open,false);cards[0].click();run('showPhoto(835)');assert.equal(ids.vnext.disabled,true);ids.viewer.dispatch('keydown',{key:'ArrowRight'});assert.equal(ids.vcount.textContent,'836 / 836');ids.viewer.dispatch('keydown',{key:'ArrowLeft'});assert.equal(ids.vcount.textContent,'835 / 836');
for(const f of documentEvents.keydown)f();assert.equal(document.documentElement.dataset.input,'keyboard');for(const f of documentEvents.pointerdown)f();assert.equal(document.documentElement.dataset.input,'pointer');run('startAlbum()');assert.equal(walk(ids.timeline).filter(x=>x.className==='card').length,836);
const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),script=fs.readFileSync(path.join(root,'album.js'),'utf8'),css=fs.readFileSync(path.join(root,'album.css'),'utf8');assert.ok(!/\sdownload[\s=>]/.test(html));assert.ok(!/fetch\(|createObjectURL|window\.open|location\.(?:href|assign)/.test(script));assert.ok(!html.includes('jumpYear'));assert.ok(!html.includes('resumeCover'));assert.ok(!html.includes('zoomBtn'));assert.equal((html.match(/id="musicBtn"/g)||[]).length,1);assert.match(css,/-webkit-touch-callout:default/);assert.ok(!/#vbar\{[^}]*overflow/.test(css));
console.log('PASS:836 unique photos;chronological years/p502;lazy loading;direct year jump;no autoplay/music toggle;viewer/focus/boundaries;stale loading/error/retry;original grid entry;inline same-image saving instructions and no download/blob/navigation;touch vs keyboard focus;idempotent render.');

// Sticky year indicator follows long-list scroll; viewer can jump across decades.
for(const [i,y] of years.entries())y.rect={top:i*1000,bottom:(i+1)*1000};ids.yearToolbar.rect={bottom:60};run('viewer.close();syncVisibleYear()');assert.equal(ids.yearSelect.value,'2004');for(const y of years)y.rect.top-=years.findIndex(x=>x.id==='year-2025')*1000;run('syncVisibleYear()');assert.equal(ids.yearSelect.value,'2025');
cards[0].click();ids.viewerYearSelect.value='2025';ids.viewerYearSelect.dispatch('change');assert.match(ids.vwhen.textContent,/^2025年/);ids.viewerYearSelect.value='2004';ids.viewerYearSelect.dispatch('change');assert.equal(ids.vcount.textContent,'1 / 836');ids.vclose.click();assert.match(css,/\.toolbar\{position:sticky;top:0/);console.log('PASS:sticky current year;viewer year jumps 2025 to 2004;exact list scroll restoration.');

assert.match(css,/grid-template-columns:repeat\(3,1fr\)/);assert.ok(!css.includes('repeat(2,'));assert.ok(!html.includes('cover-photo'));assert.ok(!html.includes('viewer-layout'));assert.ok(!html.includes('viewerContent'));assert.match(css,/#stage\{position:relative;min-width:0;min-height:0/);assert.match(css,/#stage img\{[^}]*max-width:100%;max-height:100%/);assert.ok(!script.includes("p.desc,'card-desc'"));assert.equal(cards[0].children[1].children.length,2);console.log('PASS:original seal cover, three-column square thumbnail layout, compact date/title cards, dark image viewer, no redesign panels.');
// A stationary touch is not captured; long presses and native gestures do not toggle captions.
let captures=0,releases=0,captured=false;ids.stage.setPointerCapture=()=>{captures++;captured=true};ids.stage.hasPointerCapture=()=>captured;ids.stage.releasePointerCapture=()=>{releases++;captured=false};
const pointer={pointerId:1,clientX:200,clientY:200,target:{closest:()=>null}};
run('showPhoto(0)');ids.stage.dispatch('pointerdown',pointer);assert.equal(captures,0);now+=80;ids.stage.dispatch('pointerup',pointer);assert.equal(ids.viewer.classList.contains('hideui'),true);assert.equal(ids.captionCopy.attributes['aria-hidden'],'true');
now+=2000;ids.stage.dispatch('pointerdown',pointer);now+=80;ids.stage.dispatch('pointerup',pointer);assert.equal(ids.viewer.classList.contains('hideui'),false);
ids.stage.dispatch('pointerdown',pointer);now+=700;ids.stage.dispatch('pointerup',pointer);assert.equal(ids.viewer.classList.contains('hideui'),false);assert.equal(captures,0);
let stopped=0,prevented=0;ids.stage.dispatch('click',{stopImmediatePropagation(){stopped++},preventDefault(){prevented++}});assert.equal(stopped,1);assert.equal(prevented,0);
// A context menu stays native and also suppresses a much-later synthetic click.
now+=2000;ids.stage.dispatch('pointerdown',pointer);ids.stage.dispatch('contextmenu',{preventDefault(){prevented++}});now+=5000;ids.stage.dispatch('pointerup',pointer);ids.stage.dispatch('click',{stopImmediatePropagation(){stopped++},preventDefault(){prevented++}});assert.equal(prevented,0);assert.equal(stopped,2);assert.equal(ids.viewer.classList.contains('hideui'),false);
// Only a clear horizontal movement captures; a real swipe navigates and then releases.
now+=2000;ids.stage.dispatch('pointerdown',pointer);now+=40;ids.stage.dispatch('pointermove',{...pointer,clientX:100});assert.equal(captures,1);now+=40;ids.stage.dispatch('pointerup',{...pointer,clientX:100});assert.equal(ids.vcount.textContent,'2 / 836');assert.equal(releases,1);
// Vertical movement and multi-touch are left to the browser.
ids.stage.dispatch('pointerdown',pointer);now+=40;ids.stage.dispatch('pointermove',{...pointer,clientY:280});ids.stage.dispatch('pointerup',{...pointer,clientY:280});assert.equal(captures,1);assert.equal(ids.vcount.textContent,'2 / 836');assert.equal(ids.viewer.classList.contains('hideui'),false);
ids.stage.dispatch('pointerdown',pointer);ids.stage.dispatch('pointerdown',{...pointer,pointerId:2,clientX:260});ids.stage.dispatch('pointermove',{...pointer,clientX:80});ids.stage.dispatch('pointerup',pointer);ids.stage.dispatch('pointerup',{...pointer,pointerId:2});assert.equal(captures,1);assert.equal(ids.vcount.textContent,'2 / 836');
// A hold followed by movement must not turn into a swipe/capture.
ids.stage.dispatch('pointerdown',pointer);now+=700;ids.stage.dispatch('pointermove',{...pointer,clientX:80});ids.stage.dispatch('pointerup',{...pointer,clientX:80});assert.equal(captures,1);assert.equal(ids.vcount.textContent,'2 / 836');
ids.stage.dispatch('pointerdown',pointer);ids.stage.dispatch('pointercancel',pointer);assert.equal(run('points.size'),0);
console.log('PASS:short tap; long-press duration/slop; native context menu; synthetic-click suppression without preventDefault; delayed horizontal capture; vertical/pinch passthrough.');
const imageRule=css.match(/#stage img\{([^}]+)\}/)[1];
for(const rule of ['width:auto','height:auto','max-width:100%','max-height:100%','flex:none','transform:none','transition:none','animation:none','-webkit-touch-callout:default'])assert.ok(imageRule.includes(rule),rule);
assert.ok(!/(?:^|;)width:100%/.test(imageRule));assert.ok(!/(?:^|;)height:100%/.test(imageRule));assert.match(css,/touch-action:pan-y pinch-zoom/);
assert.ok(!html.includes('saveViewer'));assert.ok(!html.includes('saveImage'));assert.ok(!css.includes('#viewer.hideui #vbar{display:none'));
assert.match(css,/\.caption-copy,\.save-help\{grid-area:1\/1/);assert.match(css,/#viewer\.hideui \.caption-copy[^}]*visibility:hidden/);assert.ok(!/#viewer\.hideui[^}]*display:none/.test(css));
assert.match(html,/>返回相册<\/button>/);assert.match(html,/<span>年份<\/span>/);console.log('PASS:clear control labels; original intrinsic image; no second save screen; caption/help reserve the same layout space.');

assert.match(css,/#viewer\[open\]\{display:grid;grid-template-rows:auto minmax\(0,1fr\) auto auto/);
for(const id of ['vclose','vprev','vnext','savePhoto','viewerYearSelect'])assert.ok(!new RegExp('#'+id+'\\{[^}]*position:absolute').test(css),id+' must not overlay photograph');
assert.ok(html.indexOf('class="viewer-topbar"')<html.indexOf('id="stage"'));assert.ok(html.indexOf('class="viewer-bottom"')>html.indexOf('id="vbar"'));
assert.ok(!script.includes('--caption-height'));assert.ok(!css.includes('#viewer.hideui #savePhoto'));
console.log('PASS:reserved top/photo/caption/bottom rows; all navigation and save controls outside photo; 44px targets retained.');
