const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');const root=path.resolve(__dirname,'..');
class Element{
 constructor(tag='div'){this.tagName=tag;this.children=[];this.events={};this.attributes={};this.dataset={};this.style={};this.hidden=false;this.disabled=false;this.value='';this.open=false;this._text='';this.className='';}
 set textContent(v){this._text=String(v)}get textContent(){return this._text+this.children.map(c=>c.textContent).join('')}
 append(...children){this.children.push(...children)}prepend(...children){this.children.unshift(...children)}setAttribute(k,v){this.attributes[k]=v}addEventListener(k,fn){(this.events[k]??=[]).push(fn)}
 dispatch(k,extra={}){for(const f of this.events[k]??[])f({preventDefault(){},...extra})}click(){if(!this.disabled)this.dispatch('click')}focus(){document.activeElement=this}scrollTo(){}getBoundingClientRect(){return this.rect||{top:0,bottom:60}}scrollIntoView(){this.scrolled=true}querySelector(tag){return this.children.find(c=>c.tagName===tag)}showModal(){this.open=true}close(){this.open=false;this.dispatch('close')}
}
const ids={},documentEvents={};const document={documentElement:new Element('html'),activeElement:null,body:new Element('body'),getElementById:id=>ids[id]??=new Element(),createElement:tag=>new Element(tag),createDocumentFragment:()=>new Element('fragment'),querySelector:s=>walk(ids.timeline).find(x=>x.className==='card'&&s.includes(x.dataset.src)),addEventListener:(name,fn)=>(documentEvents[name]??=[]).push(fn)};
function walk(el){return [el,...el.children.flatMap(walk)]}
ids.bgm=new Element('audio');ids.bgm.paused=true;let playCount=0;ids.bgm.play=()=>{playCount++;ids.bgm.paused=false;ids.bgm.dispatch('play');return Promise.resolve()};ids.bgm.pause=()=>{ids.bgm.paused=true;ids.bgm.dispatch('pause')};
const loads=[];class Image{set src(value){this._src=value;loads.push(this)}get src(){return this._src}}
const storage=new Map();const context=vm.createContext({document,Image,window:{scrollY:0,scrollTo(x,y){this.scrollY=y},addEventListener(){}},requestAnimationFrame:fn=>{fn();return 0},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},console});
for(const file of ['photos.js','album.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file});const run=code=>vm.runInContext(code,context);
assert.equal(run('PHOTOS.length'),836);assert.equal(run('new Set(PHOTOS.map(p=>p.src)).size'),836);assert.equal(run('photos.every((p,i)=>i===0||dateKey(photos[i-1])<=dateKey(p))'),true);assert.equal(loads.length,0);assert.equal(ids.startBtn.textContent,'打开相册');
ids.startBtn.click();const cards=walk(ids.timeline).filter(x=>x.className==='card');assert.equal(cards.length,836);assert.equal(ids.cover.hidden,true);assert.equal(ids.album.hidden,false);assert.equal(document.activeElement,ids.albumHeading);assert.equal(playCount,0);
ids.musicBtn.click();assert.equal(playCount,1);assert.equal(ids.musicBtn.textContent,'音乐 · 开');ids.musicBtn.click();assert.equal(ids.bgm.paused,true);assert.equal(ids.musicBtn.textContent,'音乐 · 关');
const years=walk(ids.timeline).filter(x=>x.className==='year');assert.equal(new Set(years.map(x=>x.id)).size,years.length);assert.equal(years.find(x=>walk(x).some(x=>x.dataset.src==='photos/p502.jpg')).id,'year-2017');assert.equal(cards[0].children[0].loading,'lazy');
// Direct year choice, without a second confirmation button.
ids['year-2026']=years.find(x=>x.id==='year-2026');ids.yearSelect.value='2026';ids.yearSelect.dispatch('change');assert.equal(document.activeElement,ids['year-2026'].querySelector('h2'));
run('window.scrollY=54321');cards[0].click();assert.equal(ids.viewer.open,true);assert.equal(ids.vprev.disabled,true);assert.equal(ids.vcount.textContent,'1 / 836');assert.equal(document.activeElement,ids.vclose);assert.equal(ids.imageFeedback.hidden,false);loads.at(-1).onerror();assert.equal(ids.retryImage.hidden,false);ids.retryImage.click();loads.at(-1).onload();assert.equal(ids.vimg.src,'photos/p001.jpg');
ids.vnext.click();const stale=loads.at(-1);ids.vnext.click();const latest=loads.at(-1);stale.onload();assert.equal(ids.imageFeedback.hidden,false);latest.onload();assert.equal(ids.vcount.textContent,'3 / 836');
// Save stays on the same page with a real unwrapped original image.
ids.savePhoto.click();assert.equal(ids.saveViewer.open,true);assert.equal(ids.saveImage.src,run('photos[current].src'));assert.equal(document.activeElement,ids.closeSave);const before=ids.vcount.textContent;ids.viewer.dispatch('keydown',{key:'ArrowRight'});assert.equal(ids.vcount.textContent,before);ids.closeSave.click();assert.equal(ids.saveViewer.open,false);assert.equal(document.activeElement,ids.savePhoto);assert.equal(ids.viewer.open,true);assert.equal(ids.vcount.textContent,before);
ids.savePhoto.click();ids.saveImage.dispatch('error');assert.equal(ids.saveImage.hidden,true);assert.equal(ids.saveImageStatus.hidden,false);ids.closeSave.click();ids.savePhoto.click();assert.equal(ids.saveImage.hidden,false);assert.equal(ids.saveImageStatus.hidden,true);ids.closeSave.click();
ids.vclose.click();assert.equal(ids.viewer.open,false);assert.equal(document.activeElement,cards[0]);assert.equal(document.body.style.overflow,'');assert.equal(run('window.scrollY'),54321);assert.equal(ids.startBtn.textContent,'接着看照片');assert.ok(ids.startBtn.textContent.length<10);assert.match(ids.lastViewed.textContent,/上次看到/);
ids.startBtn.click();assert.equal(ids.viewer.open,true);assert.equal(ids.vcount.textContent,'3 / 836');run('showPhoto(835)');assert.equal(ids.vnext.disabled,true);ids.viewer.dispatch('keydown',{key:'ArrowRight'});assert.equal(ids.vcount.textContent,'836 / 836');ids.viewer.dispatch('keydown',{key:'ArrowLeft'});assert.equal(ids.vcount.textContent,'835 / 836');
for(const f of documentEvents.keydown)f();assert.equal(document.documentElement.dataset.input,'keyboard');for(const f of documentEvents.pointerdown)f();assert.equal(document.documentElement.dataset.input,'pointer');run('startAlbum()');assert.equal(walk(ids.timeline).filter(x=>x.className==='card').length,836);
const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),script=fs.readFileSync(path.join(root,'album.js'),'utf8'),css=fs.readFileSync(path.join(root,'album.css'),'utf8');assert.ok(!/\sdownload[\s=>]/.test(html));assert.ok(!/fetch\(|createObjectURL|window\.open|location\.(?:href|assign)/.test(script));assert.ok(!/preventDefault[\s\S]*contextmenu/.test(script));assert.ok(!html.includes('jumpYear'));assert.ok(!html.includes('resumeCover'));assert.ok(!html.includes('zoomBtn'));assert.equal((html.match(/id="musicBtn"/g)||[]).length,1);assert.match(css,/-webkit-touch-callout:default/);assert.ok(!/#vbar\{[^}]*overflow/.test(css));
console.log('PASS:836 unique photos;chronological years/p502;lazy loading;direct year jump;no autoplay/music toggle;viewer/focus/boundaries;stale loading/error/retry;single short resume action;inline original saving with return/error retry and no download/blob/navigation;touch vs keyboard focus;idempotent render.');

// Sticky year indicator follows long-list scroll; viewer can jump across decades.
for(const [i,y] of years.entries())y.rect={top:i*1000,bottom:(i+1)*1000};ids.yearToolbar.rect={bottom:60};run('viewer.close();syncVisibleYear()');assert.equal(ids.yearSelect.value,'2004');for(const y of years)y.rect.top-=years.findIndex(x=>x.id==='year-2025')*1000;run('syncVisibleYear()');assert.equal(ids.yearSelect.value,'2025');
cards[0].click();ids.viewerYearSelect.value='2025';ids.viewerYearSelect.dispatch('change');assert.match(ids.vwhen.textContent,/^2025年/);ids.viewerYearSelect.value='2004';ids.viewerYearSelect.dispatch('change');assert.equal(ids.vcount.textContent,'1 / 836');ids.vclose.click();assert.match(css,/\.toolbar\{position:sticky;top:0/);console.log('PASS:sticky current year;viewer year jumps 2025 to 2004;exact list scroll restoration.');
